#include <iostream>

int main() {
  std::cout << "всех с 1 апреля";
}

// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
// t.me/datamines
